const BAD_PARAMETER_ERROR_CODE = 100;
const MISSING_PARAMETER_ERROR_CODE = 200;
const POSTGRESQL_ERROR_CODE = 5432;

export {
    BAD_PARAMETER_ERROR_CODE,
    MISSING_PARAMETER_ERROR_CODE,
    POSTGRESQL_ERROR_CODE,
};
